version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ArcGIS
  - Basemap
  - Brotli
  - CRMP
  - dojox
  - GeoPortal
  - geoportals
  - GRDO
  - JsDelivr
  - RMEC
  - scalebar
  - USGS
  - WKID
  - WRIA
  - xmin
  - xmax
  - ymin
  - ymax
ignoreWords:
  - ashx
  - dijit
  - jqueryui
  - mapload
  - pageview
  - zoomnextIcon
  - zoomprevIcon
import: []
