version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ArcGIS
  - Basemap
  - CRMP
  - dojox
  - GeoPortal
  - GRDO
  - JsDelivr
  - RMEC
  - USGS
ignoreWords:
  - dijit
  - pageview
import: []
