version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
allowCompoundWords: true
words:
  - ArcGIS
  - Basemap
  - Brotli
  - CRMP
  - dojox
  - GeoPortal
  - geoportals
  - GRDO
  - JsDelivr
  - lods
  - RMEC
  - scalebar
  - USGS
  - WADNR
  - WKID
  - WRIA
  - xmax
  - xmin
  - ymax
  - ymin
ignoreWords:
  - ashx
  - dijit
  - jqueryui
  - mapload
  - pageview
  - zoomnextIcon
  - zoomprevIcon
  - JURLBL
  - RTPO
import: []
