//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsdot.Grdo.Web.Mapping.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wsdot.Grdo.Web.Mapping.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///&lt;xsl:output method=&quot;html&quot; version=&quot;4.01&quot;/&gt;
        ///&lt;xsl:output doctype-public=&quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;/&gt;
        ///&lt;!--
        ///FGDC Plus.xsl (version 2.3)
        ///
        ///FGDC Plus.xsl is an XSL template that can be use with ArcGIS software
        ///to display metadata. It shows metadata elements defined in the Content 
        ///Standard for Digital Geospatial Metadata (CSDGM), aka FGDC Standard;
        ///the ESRI Profile of the Content Standard f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FGDC_Plus {
            get {
                return ResourceManager.GetString("FGDC_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///&lt;xsl:output method=&quot;html&quot; version=&quot;4.01&quot;/&gt;
        ///&lt;xsl:output doctype-public=&quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;/&gt;
        ///&lt;!--
        ///FGDC Plus.xsl (version 2.3)
        ///
        ///FGDC Plus.xsl is an XSL template that can be use with ArcGIS software
        ///to display metadata. It shows metadata elements defined in the Content 
        ///Standard for Digital Geospatial Metadata (CSDGM), aka FGDC Standard;
        ///the ESRI Profile of the Content Standard f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FgdcPlusHtml5 {
            get {
                return ResourceManager.GetString("FgdcPlusHtml5", resourceCulture);
            }
        }
    }
}
